### ISSUE TITLE
Combineren van principes, standaarden & best-practices op het gebied van frontend design & development

### ISSUE THREAD

**Issue by zainablfz** [zainablfz/i-love-web#8]
# Principes, standaarden & best-practices

Ik wil allereerst voorop stellen dat ik mijn code schrijf om responsive, accessible, performance & progressive enhanced websites te bouwen. Deze zijn erg belangrijk voor het web, aangezien dit de basis is voor een gebruiksvriendelijke website. Ik zal hieronder een lijst opnoemen wat ik allemaal gebruik en vervolgens zal ik toelichten hoe ik dit toepas in mijn code. 

- RAP/PE
- Mobile First
- Media Queries
- CSS Nesting
- UI States (feedback)
- Semantische HTML
- Component library (atomic design)
- Refactoring / DRY
- Custom Properties 
- BEM
- SVG 
- Props
- Lazy Loading
- Enhanced images

**Progressive Enhancement**:

- Laag 1: Semantische HTML
- Laag 2: Basic CSS: visueel aantrekkelijk
- Laag 3: Usability: hover states, active states, etc
- Laag 4: Animations

**Toegankelijkheid**:

- Semantische HTML (goed voor bv screenreaders)
- Img's hebben een alt tekst
- Ik gebruik semantische HTML
- Er is hoge kleurcontrast

**Performance**:

- Zo compact mogelijke code
- Gebruik maken van componenten
- Ik gebruik lazy loading op img's
- Ik zet vaste width & height waardes op evt. afbeeldingen om CLS te voorkomen
- Enhanced images 

### Mobile First

Ik maak gebruik van een **mobile-first** strategie, hierbij is het dan de bedoeling dat ik begin met het ontwikkelen voor een mobiele scherm, zodra dit gereed is enhance ik naar grotere schermen (iPad, laptop, etc.). Deze media query geef ik een `min-width` en pas ik elementen aan waar nodig. Dit is een voorbeeld hoe ik dat doe: 

``` CSS
  .card-buttons {
    width: 100%;
    display: flex;
    flex-direction: column;
    transform: scale(0.9);
    margin: 1em 1.5em 1em 0;
    gap: 1em;
    @media (min-width: 768px) {
      flex-direction: unset;
      transform: none;
      margin: 1em 1.6em 1em 1.6em;
      padding-right: 15px;
      gap: 2em;
    }
  }

```

### Alternative texts

Ik zorg ervoor dat mijn images altijd een `alt` tekst heeft, dit is goed voor de gebruikers die een screenreader gebruiken, zodat zij weten wat de context hiervan is. 

``` HTML

<img style="{`view-transition-name:${item.image.title.replace(/\s+/g, "-")}`}"
      src={item.image.url}
      alt={item.image.title}
      loading="lazy"
      width="450"
      height="321"
      title={item.image.title.replace(/\s+/g, "-")}
    />

```

### Interactive Elements 

Ik zorg ervoor dat mijn interactieve elementen altijd een `:focus` state heeft, zodat wanneer de gebruiker door een website heen gaat tabben, dit duidelijk te zien is waar hij/zij zich op de website bevindt. Hier heb ik dat bijvoorbeeld gedaan voor de button component:

``` CSS

  .btn {
    padding: 0.7em 0.5em 0.7em 0.5em;
    display: inline-flex;
    justify-content: center;
    align-items: center;
    vertical-align: middle;
    text-align: center;
    border-radius: 0.4em;
    line-height: var(--lh-1);
    text-decoration: none;
    gap: 0.5rem;
    color: var(--accent2-primary);
    border: var(--accent2-primary);
    font-size: 14px;
    box-shadow: var(--box-shadow);
    cursor: pointer;
    transition:
      box-shadow 0.2s,
      transform 0.3s;
    &:hover,
    :focus {
      box-shadow: 0px 2px 3px 0px rgba(0, 0, 0, 0.25);
      transform: scale(1.1);
      & .btn-icon {
        transform: translateX(5px);
      }
    }
    &:focus {
      border: 2px solid var(--accent2-primary);
    }
  }
``` 

## Semantische HTML

Ook maak ik gebruik van semantische HTML, dit is belangrijk voor screenreaders. Dit is een voorbeeld hiervan. Hier gebruik ik alleen een `div` om een groep elementen een styling te geven. 

``` HTML 
{#each items as item}
  <article>
    <div class="card-header">
      <p>
        <span class="location-icon">
          <IconLocationThin
            width="13"
            height="13"
            fill="var(--txt-dark-clr)"
          /></span
        >
        {item.location}
      </p>
      <p class="cocktail-price">{item.price}</p>
    </div>
    <img style="{`view-transition-name:${item.image.title.replace(/\s+/g, "-")}`}"
      src={item.image.url}
      alt={item.image.title}
      loading="lazy"
      width="450"
      height="321"
      title={item.image.title.replace(/\s+/g, "-")}
    />
    <h2>{item.title}</h2>
    <ul class="card-description">
      <li>
        <span
          ><RouteIcon
            width="20"
            height="20"
            fill="var(--page-bg-color)"
          /></span
        >
        {item.location}
      </li>
      <li>
        <span
          ><CocktailIcon
            width="20"
            height="20"
            fill="var(--page-bg-color)"
          /></span
        >
        {item.cocktailDescription}
      </li>
    </ul>
    <div class="card-buttons">
      <Button
        variant="tertiary"
        title="Boek nu"
        icon={BookIcon}
        iconColor="var(--txt-quaternary-clr)"
        size="s"
      />
      <Button
        href="/home/{item.slug}"
        variant="secondary"
        title="Lees Meer"
        icon={ArrowRightShort}
        size="s"
      />
    </div>
  </article>
{/each}

```

## UI-states

Aangezien ik aan een button component heb gewerkt, heb ik te maken gemaakt met de UI-states hiervan. Voor accessibility is de `focus` het belangrijkste, aangezien deze UI-state bedoeld is om zich te laten zien wanneer hiermee wordt genavigeerd met een toetsenbord. Hoewel deze state erg belangrijk is, heb ik ook andere states gehanteerd. Zo heb ik dit gedaan in code, ik heb deze genest voor de class met alle buttons. 

``` CSS
 .btn {
    padding: 0.7em 0.5em 0.7em 0.5em;
    display: inline-flex;
    text-align: center;
    border-radius: 0.4em;
    line-height: var(--lh-1);
    text-decoration: none;
    gap: 0.5rem;
    color: var(--accent2-primary);
    border: var(--accent2-primary);
    font-size: 14px;
    box-shadow: var(--box-shadow);
    cursor: pointer;
    transition:
      box-shadow 0.2s,
      transform 0.3s;
      &:hover,
    :focus {
      box-shadow: 0px 2px 3px 0px rgba(0, 0, 0, 0.25);
      transform: scale(1.1);
      & .btn-icon {
        transform: translateX(5px);
      }
    }
    &:focus {
      border: 2px solid var(--accent2-primary);
    }
    &:active {
      box-shadow: 0px 1px 2px 0px rgba(0, 0, 0, 0.2);
      transform: scale(0.98);
    }
    &:disabled {
      background-color: #ccc;
      color: #999;
      cursor: not-allowed;
      box-shadow: none;
      transform: none;

      & .btn-icon {
        transform: none;
      }
    }
  }

```

# Performance

## Enhanced images & lazy loading

Voor de images gebruik ik `lazy loading` om LCP te verbeteren, ook maak ik gebruik van enhanced images en geef ik een image een `webp` versie

``` HTML 
<picture>
    <source srcset=""/images/Scenery.webp"">
      <img style="{`view-transition-name:${item.image.title.replace(/\s+/g, "-")}`}"
        src="/images/Scenery.webp"
        alt={item.image.title}
        loading="lazy"
        width="450"
        height="321"
        title={item.image.title.replace(/\s+/g, "-")}
    />
</picture>

```

## Component library & props

In dit project maken wij gebruik van componenten in een component library. Dit is ingericht in het atomic design system van Brad Frost. Ook zitten de pagina's hierin verwerkt, aangezien dit dynamisch is in de CMS (Contentful)

<img width="140" alt="Image" src="https://github.com/user-attachments/assets/888941f8-0d2b-4f2c-9fb3-c38c088f365f" />

Een voorbeeld hoe ik dit gebruik: Ik heb de button component gemaakt, deze geef ik een aantal props mee, zodat deze aan te passen is. Deze importeer ik in de `TicketCard.svelte` en definieer ik deze properties:

In `Button.svelte`:

``` HTML

  <button class="btn btn-{variant} btn-{size}" {...$$restProps} on:click>
    {title}
    {#if icon}
      <span class="btn-icon">
        <svelte:component this={icon} svgColor={iconColor} {...$$restProps} />
      </span>
    {/if}
    <slot></slot>
  </button>

```
In `TicketCard.svelte`:

``` HTML

      <Button
        variant="tertiary"
        title="Boek nu"
        icon={BookIcon}
        iconColor="var(--txt-quaternary-clr)"
        size="s"
      />

```

## SVG

Ook heb ik veel gewerkt met svg's. In deze bestanden geef ik ook props mee zodat dit eventueel veranderd kan worden voor iedereen zonder dat het de svg beïnvloedt die ergens anders wordt gebruikt. Hierbij kan je denken aan de `width`, `height`, `fill`, etc. Wanneer dit dynamisch is gemaakt moet dit wel aangesproken en gedefinieerd worden op de component/pagina waar dit gebruikt wordt. Hier is een voorbeeld hoe ik dat gebruikt heb:

`BookIcon.svelte`

``` HTML 

<script>
  export let width = "";
  export let height = "";
  export let fill = "";
</script>

<svg
  {width}
  {height}
  viewBox="0 0 24 24"
  {fill}
  xmlns="http://www.w3.org/2000/svg"
>

``` 
`Button.svelte`

Hier geef ik dan aan waar de button component uit moet bestaan, zoals een icon en de resterende props (indien van toepassing):

``` HTML

<button class="btn btn-{variant} btn-{size}" {...$$restProps} on:click>
    {title}
    {#if icon}
      <span class="btn-icon">
        <svelte:component this={icon} svgColor={iconColor} {...$$restProps} />
      </span>
    {/if}
    <slot></slot>
  </button>

```

`TicketCard.svelte`

Tot slot spreek ik de button component aan en geef ik mee welke variant, title en icon(color) er moeten staan:

``` HTML

<Button
        variant="tertiary"
        title="Boek nu"
        icon={BookIcon}
        iconColor="var(--txt-quaternary-clr)"
        size="s"
      />

```

## Cumulative Layout Shift (CLS)

Ik maak gebruik van vaste width & height waardes op images. Dit doe ik om een grote CLS te voorkomen. 

``` HTML 
<picture>
    <source srcset=""/images/Scenery.webp"">
      <img style="{`view-transition-name:${item.image.title.replace(/\s+/g, "-")}`}"
        src="/images/Scenery.webp"
        alt={item.image.title}
        loading="lazy"
        width="450"
        height="321"
        title={item.image.title.replace(/\s+/g, "-")}
    />
</picture>

```
## Refactoring 

Ik heb ook veel refactored, dit zorgt voor zo'n compact mogelijke code. Dit heb ik ook gedocumenteerd in een aparte issue, hier staat wat ik heb gedaan: https://github.com/Patrickkhr/release-candidate/issues/34

## Custom Properties

Ik heb adhv het `global.css` bestand custom properties toegevoegd aan de componenten waar ik aan heb gewerkt. Zo ziet dit bestand eruit van wat ik ongeveer heb gebruikt:

``` CSS
:root {
  /* colors */
  --page-bg-color: hsl(20, 31%, 10%);
  --accent1-primary: hsl(20, 39.86%, 28.04%);
  --accent1-secondary: hsl(19.67, 31.94%, 37.45%);
  --accent1-tertiary: hsl(18.95, 32.76%, 22.75%);
  --accent1-quaternary: hsl(18.95, 20%, 62.75%);

  --accent2-primary: hsl(19.52, 100%, 75.29%);
  --accent2-secondary: hsl(19.6, 100%, 80.2%);
  --accent2-tertiary: hsl(21.23, 100%, 87.25%);
  --accent2-quaternary: hsl(18.95, 100%, 92.55%);

  --txt-dark-clr: hsl(20, 31%, 10%);
  --txt-primary-clr: hsl(19.52, 100%, 75.29%);
  --txt-secondary-clr: hsl(19.6, 100%, 80.2%);
  --txt-tertiary-clr: hsl(21.23, 100%, 87.25%);
  --txt-quaternary-clr: hsl(18.95, 100%, 92.55%);

  /* button colors */
  --btn-primary-bg: hsl(19.52, 100%, 75.29%);
  --btn-secondary-bg: hsl(18.95, 100%, 92.55%);
  --btn-primary-text-clr: hsl(20, 31%, 10%);
  --btn-secondary-hover-bg: var(--btn-primary-bg);
  --btn-secondary-border: var(--btn-primary-bg);

  /* scale factors */
  --btn-scale-xs: 0.75;
  --btn-scale-sm: 0.9;
  --btn-scale-lg: 1.3;
  --btn-scale-xl: 1.65;

  /* dynamic font sizes adapted from utopia.fyi */
  --fs-sm: clamp(0.78rem, calc(0.75rem + 0.17vw), 0.88rem);
  --fs-md: clamp(1.13rem, calc(1.04rem + 0.43vw), 1.38rem);
  --fs-lg: clamp(1.35rem, calc(1.22rem + 0.64vw), 1.72rem);
  --fs-xl: clamp(1.94rem, calc(1.69rem + 1.29vw), 2.69rem);
  --fs-2xl: clamp(2.8rem, calc(2.31rem + 2.43vw), 4.2rem);

  /* line heights */
  --lh-1: 1;
  --lh-1-1: 1.1;
  --lh-1-4: 1.4;
```
